# Generated by Django 3.0.3 on 2020-06-03 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('host', models.CharField(max_length=100)),
                ('search_url', models.CharField(max_length=200)),
                ('homepage_articles_link', models.CharField(max_length=50)),
                ('search_articles_link', models.CharField(max_length=50)),
                ('category_articles_link', models.CharField(max_length=50)),
                ('category_class', models.CharField(max_length=50)),
                ('article_title_class', models.CharField(max_length=50)),
                ('article_body_class', models.CharField(max_length=50)),
                ('article_image_class', models.CharField(max_length=50)),
                ('calification', models.IntegerField(default=100)),
            ],
        ),
    ]
