# Generated by Django 3.0.3 on 2020-06-04 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='article_body_class',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='source',
            name='article_image_class',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='source',
            name='article_title_class',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='source',
            name='category_articles_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='source',
            name='category_class',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='source',
            name='homepage_articles_link',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='source',
            name='search_articles_link',
            field=models.CharField(max_length=100),
        ),
    ]
