# Generated by Django 3.0.3 on 2020-06-15 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0002_auto_20200604_0252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='source',
            name='category_class',
        ),
    ]
