# Generated by Django 3.0.3 on 2020-06-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0004_category_sourcecategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='sourcecategory',
            name='url',
            field=models.URLField(default=None, max_length=300),
        ),
    ]
