# Generated by Django 3.0.3 on 2020-06-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0005_sourcecategory_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecategory',
            name='url',
            field=models.URLField(max_length=300),
        ),
    ]
