# Generated by Django 3.0.3 on 2020-06-15 23:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0006_auto_20200615_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sourcecategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='source.Category'),
        ),
        migrations.AlterField(
            model_name='sourcecategory',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='source.Source'),
        ),
    ]
