# Generated by Django 3.0.3 on 2020-07-09 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300)),
                ('body', models.CharField(max_length=3000)),
            ],
        ),
    ]
