# Generated by Django 3.0.3 on 2020-07-09 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_usercategory'),
        ('article', '0003_auto_20200709_0213'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='source.Source'),
        ),
    ]
