# Generated by Django 3.0.3 on 2020-07-09 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('source', '0008_usercategory'),
        ('article', '0004_article_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.URLField(default=None, max_length=400),
        ),
        migrations.AlterField(
            model_name='article',
            name='source',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to='source.Source'),
        ),
    ]
