# Generated by Django 3.0.3 on 2020-07-09 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0005_auto_20200709_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(max_length=30000),
        ),
    ]
