# Generated by Django 3.0.3 on 2020-07-09 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200709_0429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(max_length=300000),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(default=None, max_length=4000),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=3000),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=4000),
        ),
    ]
