# Generated by Django 3.0.3 on 2020-07-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20200709_1600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='body',
            field=models.CharField(max_length=3000000),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.URLField(default=None, max_length=40000),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=30000),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(max_length=40000),
        ),
    ]
